// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	config "github.com/MagicNetLab/ya-practicum-diplom/internal/config"
	mock "github.com/stretchr/testify/mock"
)

// AppConfigurator is an autogenerated mock type for the AppConfigurator type
type AppConfigurator struct {
	mock.Mock
}

// GetDBConf provides a mock function with no fields
func (_m *AppConfigurator) GetDBConf() config.DataBaseConfigurator {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDBConf")
	}

	var r0 config.DataBaseConfigurator
	if rf, ok := ret.Get(0).(func() config.DataBaseConfigurator); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.DataBaseConfigurator)
		}
	}

	return r0
}

// GetJWTConf provides a mock function with no fields
func (_m *AppConfigurator) GetJWTConf() config.JWTConfigurator {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetJWTConf")
	}

	var r0 config.JWTConfigurator
	if rf, ok := ret.Get(0).(func() config.JWTConfigurator); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.JWTConfigurator)
		}
	}

	return r0
}

// GetS3Conf provides a mock function with no fields
func (_m *AppConfigurator) GetS3Conf() config.S3Configurator {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetS3Conf")
	}

	var r0 config.S3Configurator
	if rf, ok := ret.Get(0).(func() config.S3Configurator); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.S3Configurator)
		}
	}

	return r0
}

// GetServerConf provides a mock function with no fields
func (_m *AppConfigurator) GetServerConf() config.ServerConfigurator {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetServerConf")
	}

	var r0 config.ServerConfigurator
	if rf, ok := ret.Get(0).(func() config.ServerConfigurator); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.ServerConfigurator)
		}
	}

	return r0
}

// IsValid provides a mock function with no fields
func (_m *AppConfigurator) IsValid() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsValid")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewAppConfigurator creates a new instance of AppConfigurator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppConfigurator(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppConfigurator {
	mock := &AppConfigurator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
