// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// AppConfig is an autogenerated mock type for the AppConfig type
type AppConfig struct {
	mock.Mock
}

// DBConnectionString provides a mock function with no fields
func (_m *AppConfig) DBConnectionString() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DBConnectionString")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// EncryptKey provides a mock function with no fields
func (_m *AppConfig) EncryptKey() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EncryptKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// JWTRefreshTokenLifeTime provides a mock function with no fields
func (_m *AppConfig) JWTRefreshTokenLifeTime() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for JWTRefreshTokenLifeTime")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// JWTSecret provides a mock function with no fields
func (_m *AppConfig) JWTSecret() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for JWTSecret")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// JWTTokenLifeTime provides a mock function with no fields
func (_m *AppConfig) JWTTokenLifeTime() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for JWTTokenLifeTime")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// S3AccessKey provides a mock function with no fields
func (_m *AppConfig) S3AccessKey() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for S3AccessKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// S3Bucket provides a mock function with no fields
func (_m *AppConfig) S3Bucket() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for S3Bucket")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// S3Endpoint provides a mock function with no fields
func (_m *AppConfig) S3Endpoint() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for S3Endpoint")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// S3SecretKey provides a mock function with no fields
func (_m *AppConfig) S3SecretKey() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for S3SecretKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ServerHost provides a mock function with no fields
func (_m *AppConfig) ServerHost() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServerHost")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ServerPort provides a mock function with no fields
func (_m *AppConfig) ServerPort() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServerPort")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewAppConfig creates a new instance of AppConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppConfig {
	mock := &AppConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
