// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DataBaseConfigurator is an autogenerated mock type for the DataBaseConfigurator type
type DataBaseConfigurator struct {
	mock.Mock
}

// GetDSN provides a mock function with no fields
func (_m *DataBaseConfigurator) GetDSN() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDSN")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IsValid provides a mock function with no fields
func (_m *DataBaseConfigurator) IsValid() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsValid")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewDataBaseConfigurator creates a new instance of DataBaseConfigurator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataBaseConfigurator(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataBaseConfigurator {
	mock := &DataBaseConfigurator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
