// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// S3Configurator is an autogenerated mock type for the S3Configurator type
type S3Configurator struct {
	mock.Mock
}

// GetAccessKey provides a mock function with no fields
func (_m *S3Configurator) GetAccessKey() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAccessKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetBucket provides a mock function with no fields
func (_m *S3Configurator) GetBucket() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBucket")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetEndpoint provides a mock function with no fields
func (_m *S3Configurator) GetEndpoint() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEndpoint")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetSecretKey provides a mock function with no fields
func (_m *S3Configurator) GetSecretKey() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSecretKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IsValid provides a mock function with no fields
func (_m *S3Configurator) IsValid() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsValid")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewS3Configurator creates a new instance of S3Configurator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewS3Configurator(t interface {
	mock.TestingT
	Cleanup(func())
}) *S3Configurator {
	mock := &S3Configurator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
