// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	__ "github.com/MagicNetLab/ya-practicum-diplom/internal/grpc/account/proto"

	mock "github.com/stretchr/testify/mock"
)

// AccountsServer is an autogenerated mock type for the AccountsServer type
type AccountsServer struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *AccountsServer) Create(_a0 context.Context, _a1 *__.CreateAccountRequest) (*__.CreateAccountResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *__.CreateAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.CreateAccountRequest) (*__.CreateAccountResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.CreateAccountRequest) *__.CreateAccountResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.CreateAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.CreateAccountRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *AccountsServer) Get(_a0 context.Context, _a1 *__.GetAccountRequest) (*__.GetAccountResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *__.GetAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.GetAccountRequest) (*__.GetAccountResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.GetAccountRequest) *__.GetAccountResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.GetAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.GetAccountRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: _a0, _a1
func (_m *AccountsServer) Remove(_a0 context.Context, _a1 *__.RemoveAccountRequest) (*__.RemoveAccountResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 *__.RemoveAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.RemoveAccountRequest) (*__.RemoveAccountResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.RemoveAccountRequest) *__.RemoveAccountResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.RemoveAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.RemoveAccountRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: _a0, _a1
func (_m *AccountsServer) Search(_a0 context.Context, _a1 *__.SearchAccountRequest) (*__.SearchAccountResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *__.SearchAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.SearchAccountRequest) (*__.SearchAccountResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.SearchAccountRequest) *__.SearchAccountResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.SearchAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.SearchAccountRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedAccountsServer provides a mock function with no fields
func (_m *AccountsServer) mustEmbedUnimplementedAccountsServer() {
	_m.Called()
}

// NewAccountsServer creates a new instance of AccountsServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountsServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountsServer {
	mock := &AccountsServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
