// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	__ "github.com/MagicNetLab/ya-practicum-diplom/internal/grpc/account/proto"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// AccountsClient is an autogenerated mock type for the AccountsClient type
type AccountsClient struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, in, opts
func (_m *AccountsClient) Create(ctx context.Context, in *__.CreateAccountRequest, opts ...grpc.CallOption) (*__.CreateAccountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *__.CreateAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.CreateAccountRequest, ...grpc.CallOption) (*__.CreateAccountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.CreateAccountRequest, ...grpc.CallOption) *__.CreateAccountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.CreateAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.CreateAccountRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, in, opts
func (_m *AccountsClient) Get(ctx context.Context, in *__.GetAccountRequest, opts ...grpc.CallOption) (*__.GetAccountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *__.GetAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.GetAccountRequest, ...grpc.CallOption) (*__.GetAccountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.GetAccountRequest, ...grpc.CallOption) *__.GetAccountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.GetAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.GetAccountRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: ctx, in, opts
func (_m *AccountsClient) Remove(ctx context.Context, in *__.RemoveAccountRequest, opts ...grpc.CallOption) (*__.RemoveAccountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 *__.RemoveAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.RemoveAccountRequest, ...grpc.CallOption) (*__.RemoveAccountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.RemoveAccountRequest, ...grpc.CallOption) *__.RemoveAccountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.RemoveAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.RemoveAccountRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: ctx, in, opts
func (_m *AccountsClient) Search(ctx context.Context, in *__.SearchAccountRequest, opts ...grpc.CallOption) (*__.SearchAccountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *__.SearchAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.SearchAccountRequest, ...grpc.CallOption) (*__.SearchAccountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.SearchAccountRequest, ...grpc.CallOption) *__.SearchAccountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.SearchAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.SearchAccountRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccountsClient creates a new instance of AccountsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountsClient {
	mock := &AccountsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
