// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	__ "github.com/MagicNetLab/ya-practicum-diplom/internal/grpc/card/proto"

	mock "github.com/stretchr/testify/mock"
)

// CardServer is an autogenerated mock type for the CardServer type
type CardServer struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *CardServer) Create(_a0 context.Context, _a1 *__.CreateCardRequest) (*__.CreateCardResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *__.CreateCardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.CreateCardRequest) (*__.CreateCardResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.CreateCardRequest) *__.CreateCardResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.CreateCardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.CreateCardRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *CardServer) Delete(_a0 context.Context, _a1 *__.DeleteCardRequest) (*__.DeleteCardResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *__.DeleteCardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.DeleteCardRequest) (*__.DeleteCardResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.DeleteCardRequest) *__.DeleteCardResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.DeleteCardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.DeleteCardRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *CardServer) Get(_a0 context.Context, _a1 *__.GetCardRequest) (*__.GetCardResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *__.GetCardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.GetCardRequest) (*__.GetCardResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.GetCardRequest) *__.GetCardResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.GetCardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.GetCardRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: _a0, _a1
func (_m *CardServer) List(_a0 context.Context, _a1 *__.ListCardRequest) (*__.ListCardResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *__.ListCardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.ListCardRequest) (*__.ListCardResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.ListCardRequest) *__.ListCardResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.ListCardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.ListCardRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: _a0, _a1
func (_m *CardServer) Search(_a0 context.Context, _a1 *__.SearchCardRequest) (*__.SearchCardResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *__.SearchCardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.SearchCardRequest) (*__.SearchCardResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.SearchCardRequest) *__.SearchCardResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.SearchCardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.SearchCardRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedCardServer provides a mock function with no fields
func (_m *CardServer) mustEmbedUnimplementedCardServer() {
	_m.Called()
}

// NewCardServer creates a new instance of CardServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCardServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *CardServer {
	mock := &CardServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
