// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	__ "github.com/MagicNetLab/ya-practicum-diplom/internal/grpc/card/proto"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// CardClient is an autogenerated mock type for the CardClient type
type CardClient struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, in, opts
func (_m *CardClient) Create(ctx context.Context, in *__.CreateCardRequest, opts ...grpc.CallOption) (*__.CreateCardResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *__.CreateCardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.CreateCardRequest, ...grpc.CallOption) (*__.CreateCardResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.CreateCardRequest, ...grpc.CallOption) *__.CreateCardResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.CreateCardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.CreateCardRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, in, opts
func (_m *CardClient) Delete(ctx context.Context, in *__.DeleteCardRequest, opts ...grpc.CallOption) (*__.DeleteCardResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *__.DeleteCardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.DeleteCardRequest, ...grpc.CallOption) (*__.DeleteCardResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.DeleteCardRequest, ...grpc.CallOption) *__.DeleteCardResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.DeleteCardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.DeleteCardRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, in, opts
func (_m *CardClient) Get(ctx context.Context, in *__.GetCardRequest, opts ...grpc.CallOption) (*__.GetCardResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *__.GetCardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.GetCardRequest, ...grpc.CallOption) (*__.GetCardResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.GetCardRequest, ...grpc.CallOption) *__.GetCardResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.GetCardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.GetCardRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, in, opts
func (_m *CardClient) List(ctx context.Context, in *__.ListCardRequest, opts ...grpc.CallOption) (*__.ListCardResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *__.ListCardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.ListCardRequest, ...grpc.CallOption) (*__.ListCardResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.ListCardRequest, ...grpc.CallOption) *__.ListCardResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.ListCardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.ListCardRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: ctx, in, opts
func (_m *CardClient) Search(ctx context.Context, in *__.SearchCardRequest, opts ...grpc.CallOption) (*__.SearchCardResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *__.SearchCardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.SearchCardRequest, ...grpc.CallOption) (*__.SearchCardResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.SearchCardRequest, ...grpc.CallOption) *__.SearchCardResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.SearchCardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.SearchCardRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCardClient creates a new instance of CardClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCardClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CardClient {
	mock := &CardClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
