// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	__ "github.com/MagicNetLab/ya-practicum-diplom/internal/grpc/auth/proto"

	mock "github.com/stretchr/testify/mock"
)

// AuthServer is an autogenerated mock type for the AuthServer type
type AuthServer struct {
	mock.Mock
}

// Auth provides a mock function with given fields: _a0, _a1
func (_m *AuthServer) Auth(_a0 context.Context, _a1 *__.AuthRequest) (*__.AuthResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 *__.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.AuthRequest) (*__.AuthResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.AuthRequest) *__.AuthResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.AuthRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Refresh provides a mock function with given fields: _a0, _a1
func (_m *AuthServer) Refresh(_a0 context.Context, _a1 *__.RefreshRequest) (*__.RefreshResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *__.RefreshResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.RefreshRequest) (*__.RefreshResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.RefreshRequest) *__.RefreshResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.RefreshResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.RefreshRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: _a0, _a1
func (_m *AuthServer) Register(_a0 context.Context, _a1 *__.RegRequest) (*__.RegResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *__.RegResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.RegRequest) (*__.RegResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.RegRequest) *__.RegResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.RegResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.RegRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedAuthServer provides a mock function with no fields
func (_m *AuthServer) mustEmbedUnimplementedAuthServer() {
	_m.Called()
}

// NewAuthServer creates a new instance of AuthServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServer {
	mock := &AuthServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
