// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MagicNetLab/ya-practicum-diplom/internal/repository/models"
	mock "github.com/stretchr/testify/mock"
)

// AccountRepository is an autogenerated mock type for the AccountRepository type
type AccountRepository struct {
	mock.Mock
}

// CreateAccount provides a mock function with given fields: ctx, uid, login, password, url, description
func (_m *AccountRepository) CreateAccount(ctx context.Context, uid string, login string, password string, url string, description string) (models.AccountModel, error) {
	ret := _m.Called(ctx, uid, login, password, url, description)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 models.AccountModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (models.AccountModel, error)); ok {
		return rf(ctx, uid, login, password, url, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) models.AccountModel); ok {
		r0 = rf(ctx, uid, login, password, url, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.AccountModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, uid, login, password, url, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccount provides a mock function with given fields: ctx, id
func (_m *AccountRepository) GetAccount(ctx context.Context, id string) (models.AccountModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 models.AccountModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.AccountModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.AccountModel); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.AccountModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveAccount provides a mock function with given fields: ctx, id
func (_m *AccountRepository) RemoveAccount(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchAccounts provides a mock function with given fields: ctx, search
func (_m *AccountRepository) SearchAccounts(ctx context.Context, search models.AccountSearchModel) ([]models.AccountModel, error) {
	ret := _m.Called(ctx, search)

	if len(ret) == 0 {
		panic("no return value specified for SearchAccounts")
	}

	var r0 []models.AccountModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AccountSearchModel) ([]models.AccountModel, error)); ok {
		return rf(ctx, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.AccountSearchModel) []models.AccountModel); ok {
		r0 = rf(ctx, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AccountModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.AccountSearchModel) error); ok {
		r1 = rf(ctx, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccountRepository creates a new instance of AccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountRepository {
	mock := &AccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
