// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MagicNetLab/ya-practicum-diplom/internal/repository/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AuthRepository is an autogenerated mock type for the AuthRepository type
type AuthRepository struct {
	mock.Mock
}

// CreateToken provides a mock function with given fields: ctx, uid, token, isRefresh, expired
func (_m *AuthRepository) CreateToken(ctx context.Context, uid string, token string, isRefresh bool, expired time.Time) error {
	ret := _m.Called(ctx, uid, token, isRefresh, expired)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool, time.Time) error); ok {
		r0 = rf(ctx, uid, token, isRefresh, expired)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: ctx, login, password
func (_m *AuthRepository) CreateUser(ctx context.Context, login string, password string) (models.UserModel, error) {
	ret := _m.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 models.UserModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (models.UserModel, error)); ok {
		return rf(ctx, login, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) models.UserModel); ok {
		r0 = rf(ctx, login, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.UserModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByLogin provides a mock function with given fields: ctx, login
func (_m *AuthRepository) GetUserByLogin(ctx context.Context, login string) (models.UserModel, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 models.UserModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.UserModel, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.UserModel); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.UserModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByLoginAndPassword provides a mock function with given fields: ctx, login, password
func (_m *AuthRepository) GetUserByLoginAndPassword(ctx context.Context, login string, password string) (models.UserModel, error) {
	ret := _m.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLoginAndPassword")
	}

	var r0 models.UserModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (models.UserModel, error)); ok {
		return rf(ctx, login, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) models.UserModel); ok {
		r0 = rf(ctx, login, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.UserModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByUID provides a mock function with given fields: ctx, uid
func (_m *AuthRepository) GetUserByUID(ctx context.Context, uid string) (models.UserModel, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUID")
	}

	var r0 models.UserModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.UserModel, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.UserModel); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.UserModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasLogin provides a mock function with given fields: ctx, login
func (_m *AuthRepository) HasLogin(ctx context.Context, login string) (bool, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for HasLogin")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, login)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasToken provides a mock function with given fields: ctx, Token
func (_m *AuthRepository) HasToken(ctx context.Context, Token string) (bool, error) {
	ret := _m.Called(ctx, Token)

	if len(ret) == 0 {
		panic("no return value specified for HasToken")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, Token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, Token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, Token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveToken provides a mock function with given fields: ctx, Token
func (_m *AuthRepository) RemoveToken(ctx context.Context, Token string) error {
	ret := _m.Called(ctx, Token)

	if len(ret) == 0 {
		panic("no return value specified for RemoveToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, Token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveUser provides a mock function with given fields: ctx, uid
func (_m *AuthRepository) RemoveUser(ctx context.Context, uid string) error {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveUserTokens provides a mock function with given fields: ctx, uid
func (_m *AuthRepository) RemoveUserTokens(ctx context.Context, uid string) error {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthRepository creates a new instance of AuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRepository {
	mock := &AuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
