// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MagicNetLab/ya-practicum-diplom/internal/repository/models"
	mock "github.com/stretchr/testify/mock"
)

// CardRepository is an autogenerated mock type for the CardRepository type
type CardRepository struct {
	mock.Mock
}

// CreateCard provides a mock function with given fields: ctx, card
func (_m *CardRepository) CreateCard(ctx context.Context, card models.CardModel) error {
	ret := _m.Called(ctx, card)

	if len(ret) == 0 {
		panic("no return value specified for CreateCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CardModel) error); ok {
		r0 = rf(ctx, card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCard provides a mock function with given fields: ctx, id
func (_m *CardRepository) DeleteCard(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCardByID provides a mock function with given fields: ctx, id
func (_m *CardRepository) GetCardByID(ctx context.Context, id string) (models.CardModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCardByID")
	}

	var r0 models.CardModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.CardModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.CardModel); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.CardModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchCards provides a mock function with given fields: ctx, search
func (_m *CardRepository) SearchCards(ctx context.Context, search models.CardSearch) ([]models.CardModel, error) {
	ret := _m.Called(ctx, search)

	if len(ret) == 0 {
		panic("no return value specified for SearchCards")
	}

	var r0 []models.CardModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CardSearch) ([]models.CardModel, error)); ok {
		return rf(ctx, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CardSearch) []models.CardModel); ok {
		r0 = rf(ctx, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CardModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CardSearch) error); ok {
		r1 = rf(ctx, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCardRepository creates a new instance of CardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CardRepository {
	mock := &CardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
