// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MagicNetLab/ya-practicum-diplom/internal/repository/models"
	mock "github.com/stretchr/testify/mock"
)

// FileRepository is an autogenerated mock type for the FileRepository type
type FileRepository struct {
	mock.Mock
}

// CreateFile provides a mock function with given fields: ctx, file
func (_m *FileRepository) CreateFile(ctx context.Context, file models.FilesModel) error {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for CreateFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.FilesModel) error); ok {
		r0 = rf(ctx, file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteFile provides a mock function with given fields: ctx, fileID, uid
func (_m *FileRepository) DeleteFile(ctx context.Context, fileID string, uid string) error {
	ret := _m.Called(ctx, fileID, uid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, fileID, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFile provides a mock function with given fields: ctx, fileID, uid
func (_m *FileRepository) GetFile(ctx context.Context, fileID string, uid string) (models.FilesModel, error) {
	ret := _m.Called(ctx, fileID, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 models.FilesModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (models.FilesModel, error)); ok {
		return rf(ctx, fileID, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) models.FilesModel); ok {
		r0 = rf(ctx, fileID, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.FilesModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, fileID, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchFile provides a mock function with given fields: ctx, search
func (_m *FileRepository) SearchFile(ctx context.Context, search models.FilesSearchModel) ([]models.FilesModel, error) {
	ret := _m.Called(ctx, search)

	if len(ret) == 0 {
		panic("no return value specified for SearchFile")
	}

	var r0 []models.FilesModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.FilesSearchModel) ([]models.FilesModel, error)); ok {
		return rf(ctx, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.FilesSearchModel) []models.FilesModel); ok {
		r0 = rf(ctx, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FilesModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.FilesSearchModel) error); ok {
		r1 = rf(ctx, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFileRepository creates a new instance of FileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileRepository {
	mock := &FileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
