// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MagicNetLab/ya-practicum-diplom/internal/repository/models"
	mock "github.com/stretchr/testify/mock"
)

// NoteRepository is an autogenerated mock type for the NoteRepository type
type NoteRepository struct {
	mock.Mock
}

// CreateNote provides a mock function with given fields: ctx, note
func (_m *NoteRepository) CreateNote(ctx context.Context, note models.NoteModel) error {
	ret := _m.Called(ctx, note)

	if len(ret) == 0 {
		panic("no return value specified for CreateNote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.NoteModel) error); ok {
		r0 = rf(ctx, note)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetNote provides a mock function with given fields: ctx, id, uid
func (_m *NoteRepository) GetNote(ctx context.Context, id string, uid string) (models.NoteModel, error) {
	ret := _m.Called(ctx, id, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetNote")
	}

	var r0 models.NoteModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (models.NoteModel, error)); ok {
		return rf(ctx, id, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) models.NoteModel); ok {
		r0 = rf(ctx, id, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.NoteModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveNote provides a mock function with given fields: ctx, id, uid
func (_m *NoteRepository) RemoveNote(ctx context.Context, id string, uid string) error {
	ret := _m.Called(ctx, id, uid)

	if len(ret) == 0 {
		panic("no return value specified for RemoveNote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchNote provides a mock function with given fields: ctx, search
func (_m *NoteRepository) SearchNote(ctx context.Context, search models.NoteSearchModel) ([]models.NoteModel, error) {
	ret := _m.Called(ctx, search)

	if len(ret) == 0 {
		panic("no return value specified for SearchNote")
	}

	var r0 []models.NoteModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.NoteSearchModel) ([]models.NoteModel, error)); ok {
		return rf(ctx, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.NoteSearchModel) []models.NoteModel); ok {
		r0 = rf(ctx, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.NoteModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.NoteSearchModel) error); ok {
		r1 = rf(ctx, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateNote provides a mock function with given fields: ctx, note
func (_m *NoteRepository) UpdateNote(ctx context.Context, note models.NoteModel) error {
	ret := _m.Called(ctx, note)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.NoteModel) error); ok {
		r0 = rf(ctx, note)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNoteRepository creates a new instance of NoteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNoteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NoteRepository {
	mock := &NoteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
