// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AccountSearchModel is an autogenerated mock type for the AccountSearchModel type
type AccountSearchModel struct {
	mock.Mock
}

// GetCreatedFrom provides a mock function with no fields
func (_m *AccountSearchModel) GetCreatedFrom() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCreatedFrom")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// GetCreatedTo provides a mock function with no fields
func (_m *AccountSearchModel) GetCreatedTo() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCreatedTo")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// GetDescription provides a mock function with no fields
func (_m *AccountSearchModel) GetDescription() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDescription")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetLimit provides a mock function with no fields
func (_m *AccountSearchModel) GetLimit() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLimit")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetLogin provides a mock function with no fields
func (_m *AccountSearchModel) GetLogin() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogin")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetOffset provides a mock function with no fields
func (_m *AccountSearchModel) GetOffset() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOffset")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetUID provides a mock function with no fields
func (_m *AccountSearchModel) GetUID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetURL provides a mock function with no fields
func (_m *AccountSearchModel) GetURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUpdatedFrom provides a mock function with no fields
func (_m *AccountSearchModel) GetUpdatedFrom() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUpdatedFrom")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// GetUpdatedTo provides a mock function with no fields
func (_m *AccountSearchModel) GetUpdatedTo() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUpdatedTo")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// NewAccountSearchModel creates a new instance of AccountSearchModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountSearchModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountSearchModel {
	mock := &AccountSearchModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
