// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AccountModel is an autogenerated mock type for the AccountModel type
type AccountModel struct {
	mock.Mock
}

// GetCreatedAt provides a mock function with no fields
func (_m *AccountModel) GetCreatedAt() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCreatedAt")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// GetDescription provides a mock function with no fields
func (_m *AccountModel) GetDescription() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDescription")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetID provides a mock function with no fields
func (_m *AccountModel) GetID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetLogin provides a mock function with no fields
func (_m *AccountModel) GetLogin() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogin")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetPassword provides a mock function with no fields
func (_m *AccountModel) GetPassword() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPassword")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUID provides a mock function with no fields
func (_m *AccountModel) GetUID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetURL provides a mock function with no fields
func (_m *AccountModel) GetURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUpdatedAt provides a mock function with no fields
func (_m *AccountModel) GetUpdatedAt() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUpdatedAt")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// SetCreatedAt provides a mock function with given fields: createdAt
func (_m *AccountModel) SetCreatedAt(createdAt time.Time) error {
	ret := _m.Called(createdAt)

	if len(ret) == 0 {
		panic("no return value specified for SetCreatedAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(createdAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetDescription provides a mock function with given fields: description
func (_m *AccountModel) SetDescription(description string) error {
	ret := _m.Called(description)

	if len(ret) == 0 {
		panic("no return value specified for SetDescription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetID provides a mock function with given fields: id
func (_m *AccountModel) SetID(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for SetID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetLogin provides a mock function with given fields: login
func (_m *AccountModel) SetLogin(login string) error {
	ret := _m.Called(login)

	if len(ret) == 0 {
		panic("no return value specified for SetLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(login)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetPassword provides a mock function with given fields: password
func (_m *AccountModel) SetPassword(password string) error {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for SetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetUID provides a mock function with given fields: uid
func (_m *AccountModel) SetUID(uid string) error {
	ret := _m.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for SetUID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetURL provides a mock function with given fields: url
func (_m *AccountModel) SetURL(url string) error {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for SetURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetUpdatedAt provides a mock function with given fields: updatedAt
func (_m *AccountModel) SetUpdatedAt(updatedAt time.Time) error {
	ret := _m.Called(updatedAt)

	if len(ret) == 0 {
		panic("no return value specified for SetUpdatedAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(updatedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAccountModel creates a new instance of AccountModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountModel {
	mock := &AccountModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
