// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CardModel is an autogenerated mock type for the CardModel type
type CardModel struct {
	mock.Mock
}

// GetCVC provides a mock function with no fields
func (_m *CardModel) GetCVC() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCVC")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetCreatedAt provides a mock function with no fields
func (_m *CardModel) GetCreatedAt() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCreatedAt")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// GetID provides a mock function with no fields
func (_m *CardModel) GetID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetMask provides a mock function with no fields
func (_m *CardModel) GetMask() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMask")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetMonth provides a mock function with no fields
func (_m *CardModel) GetMonth() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMonth")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetName provides a mock function with no fields
func (_m *CardModel) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetNumber provides a mock function with no fields
func (_m *CardModel) GetNumber() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNumber")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetPIN provides a mock function with no fields
func (_m *CardModel) GetPIN() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPIN")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUID provides a mock function with no fields
func (_m *CardModel) GetUID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetYear provides a mock function with no fields
func (_m *CardModel) GetYear() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetYear")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MaskNumber provides a mock function with no fields
func (_m *CardModel) MaskNumber() {
	_m.Called()
}

// Validate provides a mock function with no fields
func (_m *CardModel) Validate() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCardModel creates a new instance of CardModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCardModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *CardModel {
	mock := &CardModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
