// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NoteSearchModel is an autogenerated mock type for the NoteSearchModel type
type NoteSearchModel struct {
	mock.Mock
}

// GetContent provides a mock function with no fields
func (_m *NoteSearchModel) GetContent() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContent")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetMeta provides a mock function with no fields
func (_m *NoteSearchModel) GetMeta() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMeta")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetTitle provides a mock function with no fields
func (_m *NoteSearchModel) GetTitle() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTitle")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUID provides a mock function with no fields
func (_m *NoteSearchModel) GetUID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewNoteSearchModel creates a new instance of NoteSearchModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNoteSearchModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *NoteSearchModel {
	mock := &NoteSearchModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
