// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TokenModel is an autogenerated mock type for the TokenModel type
type TokenModel struct {
	mock.Mock
}

// GetExpired provides a mock function with no fields
func (_m *TokenModel) GetExpired() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExpired")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// GetID provides a mock function with no fields
func (_m *TokenModel) GetID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetToken provides a mock function with no fields
func (_m *TokenModel) GetToken() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUID provides a mock function with no fields
func (_m *TokenModel) GetUID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IsRefresh provides a mock function with no fields
func (_m *TokenModel) IsRefresh() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRefresh")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetExpired provides a mock function with given fields: expired
func (_m *TokenModel) SetExpired(expired time.Time) error {
	ret := _m.Called(expired)

	if len(ret) == 0 {
		panic("no return value specified for SetExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(expired)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetID provides a mock function with given fields: id
func (_m *TokenModel) SetID(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for SetID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetIsRefresh provides a mock function with given fields: refresh
func (_m *TokenModel) SetIsRefresh(refresh bool) error {
	ret := _m.Called(refresh)

	if len(ret) == 0 {
		panic("no return value specified for SetIsRefresh")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(refresh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetToken provides a mock function with given fields: token
func (_m *TokenModel) SetToken(token string) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for SetToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetUID provides a mock function with given fields: uid
func (_m *TokenModel) SetUID(uid string) error {
	ret := _m.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for SetUID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTokenModel creates a new instance of TokenModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenModel {
	mock := &TokenModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
