// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// UserModel is an autogenerated mock type for the UserModel type
type UserModel struct {
	mock.Mock
}

// GetCreatedAt provides a mock function with no fields
func (_m *UserModel) GetCreatedAt() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCreatedAt")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// GetLogin provides a mock function with no fields
func (_m *UserModel) GetLogin() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogin")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetPassword provides a mock function with no fields
func (_m *UserModel) GetPassword() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPassword")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUID provides a mock function with no fields
func (_m *UserModel) GetUID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUpdatedAt provides a mock function with no fields
func (_m *UserModel) GetUpdatedAt() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUpdatedAt")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// SetCreatedAt provides a mock function with given fields: createdAt
func (_m *UserModel) SetCreatedAt(createdAt time.Time) error {
	ret := _m.Called(createdAt)

	if len(ret) == 0 {
		panic("no return value specified for SetCreatedAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(createdAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetLogin provides a mock function with given fields: login
func (_m *UserModel) SetLogin(login string) error {
	ret := _m.Called(login)

	if len(ret) == 0 {
		panic("no return value specified for SetLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(login)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetPassword provides a mock function with given fields: password
func (_m *UserModel) SetPassword(password string) error {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for SetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetUID provides a mock function with given fields: uid
func (_m *UserModel) SetUID(uid string) error {
	ret := _m.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for SetUID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetUpdatedAt provides a mock function with given fields: updatedAt
func (_m *UserModel) SetUpdatedAt(updatedAt time.Time) error {
	ret := _m.Called(updatedAt)

	if len(ret) == 0 {
		panic("no return value specified for SetUpdatedAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(updatedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserModel creates a new instance of UserModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserModel {
	mock := &UserModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
