// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/MagicNetLab/ya-practicum-diplom/internal/services/client"

	mock "github.com/stretchr/testify/mock"
)

// AppClient is an autogenerated mock type for the AppClient type
type AppClient struct {
	mock.Mock
}

// AddAccount provides a mock function with given fields: ctx, username, password, url, meta
func (_m *AppClient) AddAccount(ctx context.Context, username string, password string, url string, meta string) error {
	ret := _m.Called(ctx, username, password, url, meta)

	if len(ret) == 0 {
		panic("no return value specified for AddAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, username, password, url, meta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddCard provides a mock function with given fields: ctx, data
func (_m *AppClient) AddCard(ctx context.Context, data client.CardData) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for AddCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.CardData) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Auth provides a mock function with given fields: ctx, username, password
func (_m *AppClient) Auth(ctx context.Context, username string, password string) (string, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CardDetail provides a mock function with given fields: ctx, id
func (_m *AppClient) CardDetail(ctx context.Context, id string) (client.CardData, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CardDetail")
	}

	var r0 client.CardData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (client.CardData, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) client.CardData); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(client.CardData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CardSearch provides a mock function with given fields: ctx, data
func (_m *AppClient) CardSearch(ctx context.Context, data client.CardSearchData) ([]client.ShortCardData, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CardSearch")
	}

	var r0 []client.ShortCardData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.CardSearchData) ([]client.ShortCardData, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.CardSearchData) []client.ShortCardData); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.ShortCardData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.CardSearchData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileAdd provides a mock function with given fields: ctx, data
func (_m *AppClient) FileAdd(ctx context.Context, data client.FileData) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for FileAdd")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.FileData) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileDownload provides a mock function with given fields: ctx, id
func (_m *AppClient) FileDownload(ctx context.Context, id string) (client.FileData, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FileDownload")
	}

	var r0 client.FileData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (client.FileData, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) client.FileData); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(client.FileData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileList provides a mock function with given fields: ctx
func (_m *AppClient) FileList(ctx context.Context) ([]client.FileData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FileList")
	}

	var r0 []client.FileData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.FileData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.FileData); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.FileData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileRemove provides a mock function with given fields: ctx, id
func (_m *AppClient) FileRemove(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FileRemove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileSearch provides a mock function with given fields: ctx, title
func (_m *AppClient) FileSearch(ctx context.Context, title string) ([]client.FileData, error) {
	ret := _m.Called(ctx, title)

	if len(ret) == 0 {
		panic("no return value specified for FileSearch")
	}

	var r0 []client.FileData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]client.FileData, error)); ok {
		return rf(ctx, title)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []client.FileData); ok {
		r0 = rf(ctx, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.FileData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccount provides a mock function with given fields: ctx, id
func (_m *AppClient) GetAccount(ctx context.Context, id string) (client.AccountData, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 client.AccountData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (client.AccountData, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) client.AccountData); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(client.AccountData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAccounts provides a mock function with given fields: ctx
func (_m *AppClient) ListAccounts(ctx context.Context) ([]client.AccountData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAccounts")
	}

	var r0 []client.AccountData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.AccountData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.AccountData); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.AccountData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCards provides a mock function with given fields: ctx
func (_m *AppClient) ListCards(ctx context.Context) ([]client.ShortCardData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCards")
	}

	var r0 []client.ShortCardData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.ShortCardData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.ShortCardData); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.ShortCardData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NoteCreate provides a mock function with given fields: ctx, data
func (_m *AppClient) NoteCreate(ctx context.Context, data client.NoteData) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for NoteCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.NoteData) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NoteDelete provides a mock function with given fields: ctx, id
func (_m *AppClient) NoteDelete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for NoteDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NoteDetail provides a mock function with given fields: ctx, id
func (_m *AppClient) NoteDetail(ctx context.Context, id string) (client.NoteData, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for NoteDetail")
	}

	var r0 client.NoteData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (client.NoteData, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) client.NoteData); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(client.NoteData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NoteSearch provides a mock function with given fields: ctx, data
func (_m *AppClient) NoteSearch(ctx context.Context, data client.NoteSearchData) ([]client.NoteData, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for NoteSearch")
	}

	var r0 []client.NoteData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.NoteSearchData) ([]client.NoteData, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.NoteSearchData) []client.NoteData); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.NoteData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.NoteSearchData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotesList provides a mock function with given fields: ctx
func (_m *AppClient) NotesList(ctx context.Context) ([]client.NoteData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NotesList")
	}

	var r0 []client.NoteData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.NoteData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.NoteData); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.NoteData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, username, password
func (_m *AppClient) Register(ctx context.Context, username string, password string) (string, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveAccount provides a mock function with given fields: ctx, username
func (_m *AppClient) RemoveAccount(ctx context.Context, username string) error {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveCard provides a mock function with given fields: ctx, id
func (_m *AppClient) RemoveCard(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchAccount provides a mock function with given fields: ctx, search
func (_m *AppClient) SearchAccount(ctx context.Context, search string) ([]client.AccountData, error) {
	ret := _m.Called(ctx, search)

	if len(ret) == 0 {
		panic("no return value specified for SearchAccount")
	}

	var r0 []client.AccountData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]client.AccountData, error)); ok {
		return rf(ctx, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []client.AccountData); ok {
		r0 = rf(ctx, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.AccountData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAppClient creates a new instance of AppClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppClient {
	mock := &AppClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
