// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TokenEntity is an autogenerated mock type for the TokenEntity type
type TokenEntity struct {
	mock.Mock
}

// GetExpired provides a mock function with no fields
func (_m *TokenEntity) GetExpired() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExpired")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// GetUID provides a mock function with no fields
func (_m *TokenEntity) GetUID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetValue provides a mock function with no fields
func (_m *TokenEntity) GetValue() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetValue")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IsRefresh provides a mock function with no fields
func (_m *TokenEntity) IsRefresh() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRefresh")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewTokenEntity creates a new instance of TokenEntity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenEntity(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenEntity {
	mock := &TokenEntity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
