// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UserEntity is an autogenerated mock type for the UserEntity type
type UserEntity struct {
	mock.Mock
	UID      string
	Login    string
	Password string
}

// GetLogin provides a mock function with no fields
func (_m UserEntity) GetLogin() string {
	return _m.Login
}

// GetPassword provides a mock function with no fields
func (_m UserEntity) GetPassword() string {
	return _m.Password
}

// GetUID provides a mock function with no fields
func (_m UserEntity) GetUID() string {
	return _m.UID
}

// NewUserEntity creates a new instance of UserEntity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserEntity(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserEntity {
	mock := &UserEntity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
