// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	__ "github.com/MagicNetLab/ya-practicum-diplom/internal/grpc/files/proto"

	mock "github.com/stretchr/testify/mock"
)

// FilesServer is an autogenerated mock type for the FilesServer type
type FilesServer struct {
	mock.Mock
}

// Download provides a mock function with given fields: _a0, _a1
func (_m *FilesServer) Download(_a0 context.Context, _a1 *__.DownloadFileRequest) (*__.DownloadFileResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 *__.DownloadFileResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.DownloadFileRequest) (*__.DownloadFileResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.DownloadFileRequest) *__.DownloadFileResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.DownloadFileResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.DownloadFileRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: _a0, _a1
func (_m *FilesServer) List(_a0 context.Context, _a1 *__.ListFilesRequest) (*__.ListFilesResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *__.ListFilesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.ListFilesRequest) (*__.ListFilesResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.ListFilesRequest) *__.ListFilesResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.ListFilesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.ListFilesRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Put provides a mock function with given fields: _a0, _a1
func (_m *FilesServer) Put(_a0 context.Context, _a1 *__.PutFileRequest) (*__.PutFileResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 *__.PutFileResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.PutFileRequest) (*__.PutFileResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.PutFileRequest) *__.PutFileResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.PutFileResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.PutFileRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: _a0, _a1
func (_m *FilesServer) Remove(_a0 context.Context, _a1 *__.RemoveFileRequest) (*__.RemoveFileResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 *__.RemoveFileResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.RemoveFileRequest) (*__.RemoveFileResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.RemoveFileRequest) *__.RemoveFileResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.RemoveFileResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.RemoveFileRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: _a0, _a1
func (_m *FilesServer) Search(_a0 context.Context, _a1 *__.SearchFilesRequest) (*__.SearchFilesResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *__.SearchFilesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.SearchFilesRequest) (*__.SearchFilesResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.SearchFilesRequest) *__.SearchFilesResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.SearchFilesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.SearchFilesRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedFilesServer provides a mock function with no fields
func (_m *FilesServer) mustEmbedUnimplementedFilesServer() {
	_m.Called()
}

// NewFilesServer creates a new instance of FilesServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFilesServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *FilesServer {
	mock := &FilesServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
