// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0
// source: internal/grpc/card/proto/cardService.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortCardModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Number string `protobuf:"bytes,3,opt,name=Number,proto3" json:"Number,omitempty"`
	Meta   string `protobuf:"bytes,4,opt,name=Meta,proto3" json:"Meta,omitempty"`
}

func (x *ShortCardModel) Reset() {
	*x = ShortCardModel{}
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortCardModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortCardModel) ProtoMessage() {}

func (x *ShortCardModel) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortCardModel.ProtoReflect.Descriptor instead.
func (*ShortCardModel) Descriptor() ([]byte, []int) {
	return file_internal_grpc_card_proto_cardService_proto_rawDescGZIP(), []int{0}
}

func (x *ShortCardModel) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ShortCardModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShortCardModel) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *ShortCardModel) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type CardModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Number string `protobuf:"bytes,3,opt,name=Number,proto3" json:"Number,omitempty"`
	Meta   string `protobuf:"bytes,4,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Month  int32  `protobuf:"varint,5,opt,name=Month,proto3" json:"Month,omitempty"`
	Year   int32  `protobuf:"varint,6,opt,name=Year,proto3" json:"Year,omitempty"`
	CVC    string `protobuf:"bytes,7,opt,name=CVC,proto3" json:"CVC,omitempty"`
	PIN    string `protobuf:"bytes,8,opt,name=PIN,proto3" json:"PIN,omitempty"`
}

func (x *CardModel) Reset() {
	*x = CardModel{}
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardModel) ProtoMessage() {}

func (x *CardModel) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardModel.ProtoReflect.Descriptor instead.
func (*CardModel) Descriptor() ([]byte, []int) {
	return file_internal_grpc_card_proto_cardService_proto_rawDescGZIP(), []int{1}
}

func (x *CardModel) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CardModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CardModel) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CardModel) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *CardModel) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *CardModel) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CardModel) GetCVC() string {
	if x != nil {
		return x.CVC
	}
	return ""
}

func (x *CardModel) GetPIN() string {
	if x != nil {
		return x.PIN
	}
	return ""
}

type GetCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_card_proto_cardService_proto_rawDescGZIP(), []int{2}
}

func (x *GetCardRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card *CardModel `protobuf:"bytes,1,opt,name=Card,proto3" json:"Card,omitempty"`
}

func (x *GetCardResponse) Reset() {
	*x = GetCardResponse{}
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardResponse) ProtoMessage() {}

func (x *GetCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardResponse.ProtoReflect.Descriptor instead.
func (*GetCardResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_card_proto_cardService_proto_rawDescGZIP(), []int{3}
}

func (x *GetCardResponse) GetCard() *CardModel {
	if x != nil {
		return x.Card
	}
	return nil
}

type CreateCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Number string `protobuf:"bytes,2,opt,name=Number,proto3" json:"Number,omitempty"`
	Meta   string `protobuf:"bytes,3,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Month  int32  `protobuf:"varint,4,opt,name=Month,proto3" json:"Month,omitempty"`
	Year   int32  `protobuf:"varint,5,opt,name=Year,proto3" json:"Year,omitempty"`
	CVC    string `protobuf:"bytes,6,opt,name=CVC,proto3" json:"CVC,omitempty"`
	PIN    string `protobuf:"bytes,7,opt,name=PIN,proto3" json:"PIN,omitempty"`
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_card_proto_cardService_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCardRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CreateCardRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *CreateCardRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *CreateCardRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateCardRequest) GetCVC() string {
	if x != nil {
		return x.CVC
	}
	return ""
}

func (x *CreateCardRequest) GetPIN() string {
	if x != nil {
		return x.PIN
	}
	return ""
}

type CreateCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card *ShortCardModel `protobuf:"bytes,1,opt,name=Card,proto3" json:"Card,omitempty"`
}

func (x *CreateCardResponse) Reset() {
	*x = CreateCardResponse{}
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardResponse) ProtoMessage() {}

func (x *CreateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardResponse.ProtoReflect.Descriptor instead.
func (*CreateCardResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_card_proto_cardService_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCardResponse) GetCard() *ShortCardModel {
	if x != nil {
		return x.Card
	}
	return nil
}

type DeleteCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_card_proto_cardService_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCardRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteCardResponse) Reset() {
	*x = DeleteCardResponse{}
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardResponse) ProtoMessage() {}

func (x *DeleteCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardResponse.ProtoReflect.Descriptor instead.
func (*DeleteCardResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_card_proto_cardService_proto_rawDescGZIP(), []int{7}
}

type SearchCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Limit  int32  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset int32  `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
}

func (x *SearchCardRequest) Reset() {
	*x = SearchCardRequest{}
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCardRequest) ProtoMessage() {}

func (x *SearchCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCardRequest.ProtoReflect.Descriptor instead.
func (*SearchCardRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_card_proto_cardService_proto_rawDescGZIP(), []int{8}
}

func (x *SearchCardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchCardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchCardRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []*ShortCardModel `protobuf:"bytes,1,rep,name=Cards,proto3" json:"Cards,omitempty"`
}

func (x *SearchCardResponse) Reset() {
	*x = SearchCardResponse{}
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCardResponse) ProtoMessage() {}

func (x *SearchCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCardResponse.ProtoReflect.Descriptor instead.
func (*SearchCardResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_card_proto_cardService_proto_rawDescGZIP(), []int{9}
}

func (x *SearchCardResponse) GetCards() []*ShortCardModel {
	if x != nil {
		return x.Cards
	}
	return nil
}

type ListCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCardRequest) Reset() {
	*x = ListCardRequest{}
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardRequest) ProtoMessage() {}

func (x *ListCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardRequest.ProtoReflect.Descriptor instead.
func (*ListCardRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_card_proto_cardService_proto_rawDescGZIP(), []int{10}
}

type ListCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []*ShortCardModel `protobuf:"bytes,1,rep,name=Cards,proto3" json:"Cards,omitempty"`
}

func (x *ListCardResponse) Reset() {
	*x = ListCardResponse{}
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardResponse) ProtoMessage() {}

func (x *ListCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_card_proto_cardService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardResponse.ProtoReflect.Descriptor instead.
func (*ListCardResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_card_proto_cardService_proto_rawDescGZIP(), []int{11}
}

func (x *ListCardResponse) GetCards() []*ShortCardModel {
	if x != nil {
		return x.Cards
	}
	return nil
}

var File_internal_grpc_card_proto_cardService_proto protoreflect.FileDescriptor

var file_internal_grpc_card_proto_cardService_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x63, 0x61, 0x72, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x6f,
	0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x22, 0x60, 0x0a,
	0x0e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x43, 0x61, 0x72, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4d,
	0x65, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x22,
	0xa9, 0x01, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x65, 0x74,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x6f,
	0x6e, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x59, 0x65, 0x61, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x59, 0x65, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x56, 0x43, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x43, 0x56, 0x43, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x4e,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x50, 0x49, 0x4e, 0x22, 0x20, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x41, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2e, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x43, 0x61, 0x72, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x04, 0x43, 0x61, 0x72, 0x64,
	0x22, 0xa1, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04,
	0x59, 0x65, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x59, 0x65, 0x61, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x43, 0x56, 0x43, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x43,
	0x56, 0x43, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x4e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x50, 0x49, 0x4e, 0x22, 0x49, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x43, 0x61,
	0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x43, 0x61, 0x72, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x04, 0x43, 0x61, 0x72, 0x64, 0x22,
	0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x55, 0x0a, 0x11, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x22, 0x4b, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x43, 0x61,
	0x72, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x22, 0x11,
	0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x49, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x32, 0x96, 0x03, 0x0a,
	0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x48, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1f, 0x2e, 0x67,
	0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x51, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x22, 0x2e, 0x67, 0x6f, 0x70, 0x68,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x51, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x22, 0x2e, 0x67,
	0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x5f, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12,
	0x22, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x20, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x5f, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x5f,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_grpc_card_proto_cardService_proto_rawDescOnce sync.Once
	file_internal_grpc_card_proto_cardService_proto_rawDescData = file_internal_grpc_card_proto_cardService_proto_rawDesc
)

func file_internal_grpc_card_proto_cardService_proto_rawDescGZIP() []byte {
	file_internal_grpc_card_proto_cardService_proto_rawDescOnce.Do(func() {
		file_internal_grpc_card_proto_cardService_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_grpc_card_proto_cardService_proto_rawDescData)
	})
	return file_internal_grpc_card_proto_cardService_proto_rawDescData
}

var file_internal_grpc_card_proto_cardService_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_grpc_card_proto_cardService_proto_goTypes = []any{
	(*ShortCardModel)(nil),     // 0: gophkeeper_grpc.ShortCardModel
	(*CardModel)(nil),          // 1: gophkeeper_grpc.CardModel
	(*GetCardRequest)(nil),     // 2: gophkeeper_grpc.GetCardRequest
	(*GetCardResponse)(nil),    // 3: gophkeeper_grpc.GetCardResponse
	(*CreateCardRequest)(nil),  // 4: gophkeeper_grpc.CreateCardRequest
	(*CreateCardResponse)(nil), // 5: gophkeeper_grpc.CreateCardResponse
	(*DeleteCardRequest)(nil),  // 6: gophkeeper_grpc.DeleteCardRequest
	(*DeleteCardResponse)(nil), // 7: gophkeeper_grpc.DeleteCardResponse
	(*SearchCardRequest)(nil),  // 8: gophkeeper_grpc.SearchCardRequest
	(*SearchCardResponse)(nil), // 9: gophkeeper_grpc.SearchCardResponse
	(*ListCardRequest)(nil),    // 10: gophkeeper_grpc.ListCardRequest
	(*ListCardResponse)(nil),   // 11: gophkeeper_grpc.ListCardResponse
}
var file_internal_grpc_card_proto_cardService_proto_depIdxs = []int32{
	1,  // 0: gophkeeper_grpc.GetCardResponse.Card:type_name -> gophkeeper_grpc.CardModel
	0,  // 1: gophkeeper_grpc.CreateCardResponse.Card:type_name -> gophkeeper_grpc.ShortCardModel
	0,  // 2: gophkeeper_grpc.SearchCardResponse.Cards:type_name -> gophkeeper_grpc.ShortCardModel
	0,  // 3: gophkeeper_grpc.ListCardResponse.Cards:type_name -> gophkeeper_grpc.ShortCardModel
	2,  // 4: gophkeeper_grpc.Card.Get:input_type -> gophkeeper_grpc.GetCardRequest
	4,  // 5: gophkeeper_grpc.Card.Create:input_type -> gophkeeper_grpc.CreateCardRequest
	6,  // 6: gophkeeper_grpc.Card.Delete:input_type -> gophkeeper_grpc.DeleteCardRequest
	8,  // 7: gophkeeper_grpc.Card.Search:input_type -> gophkeeper_grpc.SearchCardRequest
	10, // 8: gophkeeper_grpc.Card.List:input_type -> gophkeeper_grpc.ListCardRequest
	3,  // 9: gophkeeper_grpc.Card.Get:output_type -> gophkeeper_grpc.GetCardResponse
	5,  // 10: gophkeeper_grpc.Card.Create:output_type -> gophkeeper_grpc.CreateCardResponse
	7,  // 11: gophkeeper_grpc.Card.Delete:output_type -> gophkeeper_grpc.DeleteCardResponse
	9,  // 12: gophkeeper_grpc.Card.Search:output_type -> gophkeeper_grpc.SearchCardResponse
	11, // 13: gophkeeper_grpc.Card.List:output_type -> gophkeeper_grpc.ListCardResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_grpc_card_proto_cardService_proto_init() }
func file_internal_grpc_card_proto_cardService_proto_init() {
	if File_internal_grpc_card_proto_cardService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_grpc_card_proto_cardService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_card_proto_cardService_proto_goTypes,
		DependencyIndexes: file_internal_grpc_card_proto_cardService_proto_depIdxs,
		MessageInfos:      file_internal_grpc_card_proto_cardService_proto_msgTypes,
	}.Build()
	File_internal_grpc_card_proto_cardService_proto = out.File
	file_internal_grpc_card_proto_cardService_proto_rawDesc = nil
	file_internal_grpc_card_proto_cardService_proto_goTypes = nil
	file_internal_grpc_card_proto_cardService_proto_depIdxs = nil
}
