// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	__ "github.com/MagicNetLab/ya-practicum-diplom/internal/grpc/note/proto"

	mock "github.com/stretchr/testify/mock"
)

// NoteServer is an autogenerated mock type for the NoteServer type
type NoteServer struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *NoteServer) Create(_a0 context.Context, _a1 *__.CreateNoteRequest) (*__.CreateNoteResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *__.CreateNoteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.CreateNoteRequest) (*__.CreateNoteResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.CreateNoteRequest) *__.CreateNoteResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.CreateNoteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.CreateNoteRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *NoteServer) Get(_a0 context.Context, _a1 *__.GetNoteRequest) (*__.GetNoteResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *__.GetNoteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.GetNoteRequest) (*__.GetNoteResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.GetNoteRequest) *__.GetNoteResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.GetNoteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.GetNoteRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: _a0, _a1
func (_m *NoteServer) List(_a0 context.Context, _a1 *__.ListNoteRequest) (*__.ListNoteResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *__.ListNoteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.ListNoteRequest) (*__.ListNoteResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.ListNoteRequest) *__.ListNoteResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.ListNoteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.ListNoteRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: _a0, _a1
func (_m *NoteServer) Remove(_a0 context.Context, _a1 *__.RemoveNoteRequest) (*__.RemoveNoteResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 *__.RemoveNoteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.RemoveNoteRequest) (*__.RemoveNoteResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.RemoveNoteRequest) *__.RemoveNoteResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.RemoveNoteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.RemoveNoteRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: _a0, _a1
func (_m *NoteServer) Search(_a0 context.Context, _a1 *__.SearchNoteRequest) (*__.SearchNoteResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *__.SearchNoteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.SearchNoteRequest) (*__.SearchNoteResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.SearchNoteRequest) *__.SearchNoteResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.SearchNoteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.SearchNoteRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedNoteServer provides a mock function with no fields
func (_m *NoteServer) mustEmbedUnimplementedNoteServer() {
	_m.Called()
}

// NewNoteServer creates a new instance of NoteServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNoteServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *NoteServer {
	mock := &NoteServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
